Автор материала: Зраев Артем.

Можно использовать в каких угодно целях.

<b> В задании нужно загрузить датасет с данными оттока и ответить на несколько вопросов (написать код). При этом сам датасет уже есть и его необязательно качать с репозитория</b>

Цель задания: проверить базовые навыки работы студентов с Pandas, умение проводить такой же базовый EDA (exploratory data analysis), делать feature engineering и обучать и валидировать модель.

Список столбцов с типами данных в датасете:

- customerID           object
- gender               object
- SeniorCitizen         int64
- Partner              object
- Dependents           object
- tenure                int64
- PhoneService         object
- MultipleLines        object
- InternetService      object
- OnlineSecurity       object
- OnlineBackup         object
- DeviceProtection     object
- TechSupport          object
- StreamingTV          object
- StreamingMovies      object
- Contract             object
- PaperlessBilling     object
- PaymentMethod        object
- MonthlyCharges      float64
- TotalCharges         object
- Churn                object

In [128]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')
DATASET_PATH = '/content/drive/My Drive/WA_Fn-UseC_-Telco-Customer-Churn.csv'
df = pd.read_csv(DATASET_PATH)
df.head(10)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes
5  9305-CDSKC  Female              0  ...          99.65        820.5    Yes
6  1452-KIOVK    Male              0  ...          89.10       1949.4     No
7  6713-OKOMC  Female              0  ...          29.75        301.9     No
8  7892-POOKP  Female              0  ...         104.80      3046.05    Yes
9  6388-TABGU    Male              0  ...          56.15      3487.95     No

[10 rows x 21 columns]

##### 1. Какое соотношение мужчин и женщин в представленном наборе данных?

In [129]:
m = df.gender[df.gender == 'Male'].count()
f = df.gender[df.gender == 'Female'].count()
res_m = (m * 100)/df['gender'].count()
res_f = (f * 100)/df['gender'].count()
print (f'{res_m} % of men and {res_f} % of women')

50.475649581144395 % of men and 49.524350418855605 % of women


##### 2. Какое количество уникальных значений у поля InternetService?

In [130]:
df['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

##### 3. Выведите статистики по полю TotalCharges (median, mean, std).

In [131]:
#df['TotalCharges'] = pd.to_numeric(df['TotalCharges'].str.replace('\D', ''), errors='coerce')
#median = df['TotalCharges'].median()
#mode = df['TotalCharges'].mode().iloc[0]
#std = df['TotalCharges'].std()
#print (f'Median of Total Charges:{median}\nMode of Total Charges:{mode}\nSTD of Total Charges:{std}')

В чем странность того, что вы получили? (подсказка: смотреть нужно на тип данных)

##### 4. Сделайте замену значений поля PhoneService  на числовые (Yes->1, No->0)

In [132]:
binary_to_numbers = {'No': 0, 'Yes': 1}
df['PhoneService'] = df['PhoneService'].replace(binary_to_numbers)

##### 5. Сделайте замену пробелов в поле TotalCharges на np.nan и приведите поле к типу данных float32. Затем заполните оставшиеся пропуски значением 0 с помощью метода fillna у столбца. Снова выведите статистики и сравните с тем, что вы видели в вопросе 3

In [133]:
space_to_none = {' ': np.nan}
df['TotalCharges'] = df['TotalCharges'].replace(space_to_none)
df.loc[df['TotalCharges'].isna(), 'TotalCharges'] = 0
df['TotalCharges'] = df['TotalCharges'].astype(np.float32)
#df['TotalCharges'].fillna(1)
median = df['TotalCharges'].median()
mode = df['TotalCharges'].mode().iloc[0]
std = df['TotalCharges'].std()
print (f'Median of Total Charges:{median}\nMode of Total Charges:{mode}\nSTD of Total Charges:{std}')

df['TotalCharges'].count()

Median of Total Charges:1394.550048828125
Mode of Total Charges:0.0
STD of Total Charges:2266.79443359375


7043

##### 6. Сделайте замену значений поля Churn на числовые (Yes -> 1, No - 0)

In [134]:
df['Churn'] = df['Churn'].replace(binary_to_numbers)

##### 7. Сделайте замену значений полей StreamingMovies, StreamingTV, TechSupport  на числовые (Yes -> 1, No -> 0, No internet service->0)

In [135]:
more_btn = {'No': 0, 'Yes': 1, 'No internet service':0}
df['StreamingMovies'] = df['StreamingMovies'].replace(more_btn)
df['StreamingTV'] = df['StreamingTV'].replace(more_btn)
df['TechSupport'] = df['TechSupport'].replace(more_btn)

##### 8. Заполните пропуски в поле PhoneService значением 0

In [136]:
df.loc[df['PhoneService'].isna(), 'PhoneService'] = 0


#### 8. Для нашего датасета оставьте только указанный ниже список полей, удалив все другие и выведите верхние 3 строки

In [137]:
columns = ['gender', 'tenure', 'PhoneService', 'TotalCharges',
           'StreamingMovies', 'StreamingTV', 'TechSupport', 'Churn']
#Ваш код здесь

new_df = df[columns]
new_df.head(3)
new_df.isna()

gender  tenure  PhoneService  ...  StreamingTV  TechSupport  Churn
0      False   False         False  ...        False        False  False
1      False   False         False  ...        False        False  False
2      False   False         False  ...        False        False  False
3      False   False         False  ...        False        False  False
4      False   False         False  ...        False        False  False
...      ...     ...           ...  ...          ...          ...    ...
7038   False   False         False  ...        False        False  False
7039   False   False         False  ...        False        False  False
7040   False   False         False  ...        False        False  False
7041   False   False         False  ...        False        False  False
7042   False   False         False  ...        False        False  False

[7043 rows x 8 columns]

##### 9. Разделите датасет на тренировочную и тестовую выборку (подсказка - воспользуйтесь train_test_split из sklearn.model_selection. Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

In [138]:
from sklearn.model_selection import train_test_split

features = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport']
target = 'Churn'
X = new_df.drop(columns=target)
y = new_df[target]
X_train, X_valid, y_train, y_valid = train_test_split(X, y, test_size=0.33, shuffle=True, random_state=21)


In [139]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4718 entries, 6790 to 5327
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   gender           4718 non-null   object 
 1   tenure           4718 non-null   int64  
 2   PhoneService     4718 non-null   int64  
 3   TotalCharges     4718 non-null   float32
 4   StreamingMovies  4718 non-null   int64  
 5   StreamingTV      4718 non-null   int64  
 6   TechSupport      4718 non-null   int64  
dtypes: float32(1), int64(5), object(1)
memory usage: 276.4+ KB


##### 10. соберите pipeline для поля gender (нужно разобраться и изучить https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html ) из классов ColumnSelector и OHEEncoder, которые уже написаны ниже заранее

In [140]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class ColumnSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.key]
    
class NumberSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    Use on numeric columns in the data
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[[self.key]]
    
class OHEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key
        self.columns = []

    def fit(self, X, y=None):
        self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
        return self

    def transform(self, X):
        X = pd.get_dummies(X, prefix=self.key)
        test_columns = [col for col in X.columns]
        for col_ in test_columns:
            if col_ not in self.columns:
                X[col_] = 0
        return X[self.columns]

gender = Pipeline([
                ('selector', ColumnSelector(key='gender')),
                ('ohe', OHEEncoder(key='gender'))
            ])

##### 11. Вызовите метод fit_transform у пайплайна gender и передайте туда нашу тренировочную выборку (пример по ссылке из документации https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit)

In [141]:
gender.fit_transform(X_train)


gender_Female  gender_Male
6790              1            0
4156              0            1
710               0            1
1335              0            1
1661              1            0
...             ...          ...
6512              0            1
48                0            1
772               1            0
5944              0            1
5327              1            0

[4718 rows x 2 columns]

##### 12. Здесь код писать уже не нужно (все сделано за вас). К полю tenure применяем StandardScaler (нормируем и центрируем). Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
Вопрос - в каких случаях это может быть полезно?

In [142]:
from sklearn.preprocessing import StandardScaler

tenure =  Pipeline([
                ('selector', NumberSelector(key='tenure')),
                ('standard', StandardScaler())
            ])

In [143]:
tenure.fit_transform(X_train)

array([[ 1.41070019],
       [-1.27583342],
       [-1.27583342],
       ...,
       [-1.27583342],
       [-0.82807782],
       [-0.09538683]])

##### 13. Напишите аналогичный (как для tenure) преобразователь поля TotalCharges

In [144]:
TotalCharges =  Pipeline([
                ('selector', NumberSelector(key='TotalCharges')),
                ('standard', StandardScaler())
            ])

In [145]:
TotalCharges.fit_transform(X_train)

array([[-0.2144687 ],
       [-0.99494016],
       [-0.99502844],
       ...,
       [-0.9948741 ],
       [-0.7149914 ],
       [-0.73949957]], dtype=float32)

Объединение всех "кубиков" очень легко сделать таким образом

In [146]:
from sklearn.pipeline import FeatureUnion

number_features = Pipeline([
                ('selector', ColumnSelector(key=['PhoneService',
                                                 'StreamingMovies', 'StreamingTV', 
                                                 'TechSupport']))
            ])

In [147]:
number_features.fit_transform(X_train)

PhoneService  StreamingMovies  StreamingTV  TechSupport
6790             1                0            0            0
4156             1                0            0            0
710              1                0            0            0
1335             1                0            0            0
1661             1                1            1            0
...            ...              ...          ...          ...
6512             1                0            0            1
48               1                1            1            1
772              1                0            0            0
5944             1                0            0            1
5327             1                0            0            0

[4718 rows x 4 columns]

In [148]:
feats = FeatureUnion([('tenure', tenure), ('TotalCharges', TotalCharges),
                      ('continuos_features', number_features),
                      ('gender', gender)])
feature_processing = Pipeline([('feats', feats)])

In [149]:
feature_processing.fit_transform(X_train)

array([[ 1.41070019, -0.2144687 ,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [-1.27583342, -0.99494016,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [-1.27583342, -0.99502844,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       ...,
       [-1.27583342, -0.99487412,  1.        , ...,  0.        ,
         1.        ,  0.        ],
       [-0.82807782, -0.71499139,  1.        , ...,  1.        ,
         0.        ,  1.        ],
       [-0.09538683, -0.73949957,  1.        , ...,  0.        ,
         1.        ,  0.        ]])

На этом этапе что мы сделали:
1. написали преобразователь поля gender, который делает OHE кодирование
2. написали преобразователь для поля tenure, который нормирует и центрирует его 
3. повторили п. 2 для поля TotalCharges
3. для всех остальных просто взяли признаки как они есть, без изменений

У нас уже готов наш пайплайн, который преобразовывает признаки. Давайте обучим модель поверх него. В качестве модели возьмем RandomForestClassifier

In [150]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features',feats),
    ('classifier', RandomForestClassifier(random_state = 42)),
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('tenure',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='tenure')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('TotalCharges',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='TotalCharges')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('continuos_features',
                                                 Pipeline(steps=[('selector',
          

##### 14. Сделайте прогноз вероятности оттока для X_test с помощью нашего предобученного на предыдущем шаге пайплайна и убедитесь что вам возвращаются вероятности для 2 классов

In [151]:
preds = pipeline.predict(X_valid)
print(preds)

[1 0 0 ... 0 0 0]


##### 15. Посчитайте метрики качества получившейся модели (roc_auc, logloss)

In [152]:
from sklearn.metrics import roc_auc_score, log_loss

roc = roc_auc_score(y_valid,preds)
ll = log_loss(y_valid, preds)
print(roc, ll)

0.6606706605761796 8.408232663267766


### Сохраним наш пайплайн

In [153]:
import dill
with open("model_RF.dill", "wb") as f:
    dill.dump(pipeline, f)